package com.estate.real_estate.domain;
// Generated Aug 30, 2018 1:31:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name="booking"
    ,catalog="db_estate"
)
public class Booking  implements java.io.Serializable {


     private Integer bookId;
     private PaymentMethod paymentMethod;
     private PaymentType paymentType;
     private ProType proType;
     private User user;
     private Date dueDate;
     private double dueAmount;
     private Date datePaid;
     private double amountPaid;
     private String paymentStatus;

    public Booking() {
    }

    public Booking(PaymentMethod paymentMethod, PaymentType paymentType, ProType proType, User user, Date dueDate, double dueAmount, Date datePaid, double amountPaid, String paymentStatus) {
       this.paymentMethod = paymentMethod;
       this.paymentType = paymentType;
       this.proType = proType;
       this.user = user;
       this.dueDate = dueDate;
       this.dueAmount = dueAmount;
       this.datePaid = datePaid;
       this.amountPaid = amountPaid;
       this.paymentStatus = paymentStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="book_id", unique=true, nullable=false)
    public Integer getBookId() {
        return this.bookId;
    }
    
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pay_method_id", nullable=false)
    public PaymentMethod getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pay_type_id", nullable=false)
    public PaymentType getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(PaymentType paymentType) {
        this.paymentType = paymentType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pro_type_id", nullable=false)
    public ProType getProType() {
        return this.proType;
    }
    
    public void setProType(ProType proType) {
        this.proType = proType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="due_date", nullable=false, length=10)
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    
    @Column(name="due_amount", nullable=false, precision=22, scale=0)
    public double getDueAmount() {
        return this.dueAmount;
    }
    
    public void setDueAmount(double dueAmount) {
        this.dueAmount = dueAmount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_paid", nullable=false, length=10)
    public Date getDatePaid() {
        return this.datePaid;
    }
    
    public void setDatePaid(Date datePaid) {
        this.datePaid = datePaid;
    }

    
    @Column(name="amount_paid", nullable=false, precision=22, scale=0)
    public double getAmountPaid() {
        return this.amountPaid;
    }
    
    public void setAmountPaid(double amountPaid) {
        this.amountPaid = amountPaid;
    }

    
    @Column(name="payment_status", nullable=false, length=20)
    public String getPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }




}


