package com.estate.real_estate.domain;
// Generated Aug 30, 2018 1:31:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inquiry generated by hbm2java
 */
@Entity
@Table(name="inquiry"
    ,catalog="db_estate"
)
public class Inquiry  implements java.io.Serializable {


     private Integer inqId;
     private User user;
     private String inqName;
     private String inqTitle;
     private String inqDes;
     private String inqContact;
     private String inqEmail;
     private Date inqDate;

    public Inquiry() {
    }

    public Inquiry(User user, String inqName, String inqTitle, String inqDes, String inqContact, String inqEmail, Date inqDate) {
       this.user = user;
       this.inqName = inqName;
       this.inqTitle = inqTitle;
       this.inqDes = inqDes;
       this.inqContact = inqContact;
       this.inqEmail = inqEmail;
       this.inqDate = inqDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="inq_id", unique=true, nullable=false)
    public Integer getInqId() {
        return this.inqId;
    }
    
    public void setInqId(Integer inqId) {
        this.inqId = inqId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="inq_name", nullable=false, length=30)
    public String getInqName() {
        return this.inqName;
    }
    
    public void setInqName(String inqName) {
        this.inqName = inqName;
    }

    
    @Column(name="inq_title", nullable=false, length=30)
    public String getInqTitle() {
        return this.inqTitle;
    }
    
    public void setInqTitle(String inqTitle) {
        this.inqTitle = inqTitle;
    }

    
    @Column(name="inq_des", nullable=false, length=90)
    public String getInqDes() {
        return this.inqDes;
    }
    
    public void setInqDes(String inqDes) {
        this.inqDes = inqDes;
    }

    
    @Column(name="inq_contact", nullable=false, length=25)
    public String getInqContact() {
        return this.inqContact;
    }
    
    public void setInqContact(String inqContact) {
        this.inqContact = inqContact;
    }

    
    @Column(name="inq_email", nullable=false, length=30)
    public String getInqEmail() {
        return this.inqEmail;
    }
    
    public void setInqEmail(String inqEmail) {
        this.inqEmail = inqEmail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="inq_date", nullable=false, length=10)
    public Date getInqDate() {
        return this.inqDate;
    }
    
    public void setInqDate(Date inqDate) {
        this.inqDate = inqDate;
    }




}


