package com.estate.real_estate.domain;
// Generated Aug 30, 2018 1:31:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentMethod generated by hbm2java
 */
@Entity
@Table(name="payment_method"
    ,catalog="db_estate"
)
public class PaymentMethod  implements java.io.Serializable {


     private Integer payMethodId;
     private String payMethod;
     private Set<Booking> bookings = new HashSet<Booking>(0);

    public PaymentMethod() {
    }

	
    public PaymentMethod(String payMethod) {
        this.payMethod = payMethod;
    }
    public PaymentMethod(String payMethod, Set<Booking> bookings) {
       this.payMethod = payMethod;
       this.bookings = bookings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pay_method_id", unique=true, nullable=false)
    public Integer getPayMethodId() {
        return this.payMethodId;
    }
    
    public void setPayMethodId(Integer payMethodId) {
        this.payMethodId = payMethodId;
    }

    
    @Column(name="pay_method", nullable=false, length=15)
    public String getPayMethod() {
        return this.payMethod;
    }
    
    public void setPayMethod(String payMethod) {
        this.payMethod = payMethod;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paymentMethod")
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }




}


