package com.estate.real_estate.domain;
// Generated Aug 30, 2018 1:31:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentType generated by hbm2java
 */
@Entity
@Table(name="payment_type"
    ,catalog="db_estate"
)
public class PaymentType  implements java.io.Serializable {


     private Integer payTypeId;
     private String payType;
     private Set<Booking> bookings = new HashSet<Booking>(0);

    public PaymentType() {
    }

	
    public PaymentType(String payType) {
        this.payType = payType;
    }
    public PaymentType(String payType, Set<Booking> bookings) {
       this.payType = payType;
       this.bookings = bookings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pay_type_id", unique=true, nullable=false)
    public Integer getPayTypeId() {
        return this.payTypeId;
    }
    
    public void setPayTypeId(Integer payTypeId) {
        this.payTypeId = payTypeId;
    }

    
    @Column(name="pay_type", nullable=false, length=15)
    public String getPayType() {
        return this.payType;
    }
    
    public void setPayType(String payType) {
        this.payType = payType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paymentType")
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }




}


