package com.estate.real_estate.domain;
// Generated Aug 30, 2018 1:31:48 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Property generated by hbm2java
 */
@Entity
@Table(name="property"
    ,catalog="db_estate"
)
public class Property  implements java.io.Serializable {


     private Integer proId;
     private Area area;
     private City city;
     private ProType proType;
     private String proName;
     private String proAddress;
     private int sqFt;
     private double price;
     private int proStatus;
     private String proDes;
     private int floor;
     private byte[] image;
     private int quantity;

    public Property() {
    }

    public Property(Area area, City city, ProType proType, String proName, String proAddress, int sqFt, double price, int proStatus, String proDes, int floor, byte[] image, int quantity) {
       this.area = area;
       this.city = city;
       this.proType = proType;
       this.proName = proName;
       this.proAddress = proAddress;
       this.sqFt = sqFt;
       this.price = price;
       this.proStatus = proStatus;
       this.proDes = proDes;
       this.floor = floor;
       this.image = image;
       this.quantity = quantity;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pro_id", unique=true, nullable=false)
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="area_id", nullable=false)
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="city_id", nullable=false)
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pro_type_id", nullable=false)
    public ProType getProType() {
        return this.proType;
    }
    
    public void setProType(ProType proType) {
        this.proType = proType;
    }

    
    @Column(name="pro_name", nullable=false, length=30)
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }

    
    @Column(name="pro_address", nullable=false, length=45)
    public String getProAddress() {
        return this.proAddress;
    }
    
    public void setProAddress(String proAddress) {
        this.proAddress = proAddress;
    }

    
    @Column(name="sq_ft", nullable=false)
    public int getSqFt() {
        return this.sqFt;
    }
    
    public void setSqFt(int sqFt) {
        this.sqFt = sqFt;
    }

    
    @Column(name="price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    
    @Column(name="pro_status", nullable=false)
    public int getProStatus() {
        return this.proStatus;
    }
    
    public void setProStatus(int proStatus) {
        this.proStatus = proStatus;
    }

    
    @Column(name="pro_des", nullable=false, length=45)
    public String getProDes() {
        return this.proDes;
    }
    
    public void setProDes(String proDes) {
        this.proDes = proDes;
    }

    
    @Column(name="floor", nullable=false)
    public int getFloor() {
        return this.floor;
    }
    
    public void setFloor(int floor) {
        this.floor = floor;
    }

    
    @Column(name="image", nullable=false)
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


