package com.estate.real_estate.domain;
// Generated Aug 30, 2018 1:31:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProType generated by hbm2java
 */
@Entity
@Table(name="pro_type"
    ,catalog="db_estate"
)
public class ProType  implements java.io.Serializable {


     private Integer proTypeId;
     private String proType;
     private Set<Booking> bookings = new HashSet<Booking>(0);
     private Set<Property> properties = new HashSet<Property>(0);

    public ProType() {
    }

	
    public ProType(String proType) {
        this.proType = proType;
    }
    public ProType(String proType, Set<Booking> bookings, Set<Property> properties) {
       this.proType = proType;
       this.bookings = bookings;
       this.properties = properties;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pro_type_id", unique=true, nullable=false)
    public Integer getProTypeId() {
        return this.proTypeId;
    }
    
    public void setProTypeId(Integer proTypeId) {
        this.proTypeId = proTypeId;
    }

    
    @Column(name="pro_type", nullable=false, length=30)
    public String getProType() {
        return this.proType;
    }
    
    public void setProType(String proType) {
        this.proType = proType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proType")
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proType")
    public Set<Property> getProperties() {
        return this.properties;
    }
    
    public void setProperties(Set<Property> properties) {
        this.properties = properties;
    }




}


